---
# Add Git known hosts

- name: Add Git Known hosts
  known_hosts:
    name: "{{ item.name }}"
    key: "{{ item.key | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  become: true
  become_user: "{{ git_user }}"
  with_items: "{{ git_known_hosts }}"